services:
  frontend:
    image: survey-platform-frontend:latest
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "18080:80"
    depends_on:
      - backend
    networks:
      - survey-network

  backend:
    image: survey-platform-backend:latest
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - survey-network

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge
