ARG DOCKER_REGISTRY=docker.m.daocloud.io/library

FROM ${DOCKER_REGISTRY}/maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

COPY settings.xml pom.xml ./
RUN mvn -B -ntp -s settings.xml -DskipTests dependency:go-offline dependency:resolve-plugins

COPY src ./src
RUN mvn -B -ntp -s settings.xml -DskipTests package

FROM ${DOCKER_REGISTRY}/eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
